version: "3"
services:

  fronted:
    image: nginx
    container_name: fcc-fronted
    ports:
      - "8088:80"
    volumes:
      - ../dist:/usr/share/nginx/html
      - ./app.conf:/etc/nginx/conf.d/default.conf
    restart: always